import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import {
  buildSharedReportPayload,
  newShareToken,
  type SharedReportPayload,
} from "@/lib/shared-report";
import type {
  BuyerStressTestResult,
  IdeaAnalysis,
  PricingRecommendation,
} from "@/types";
import type { ProductContext } from "@/lib/product-context";
import type { FounderBriefExtras } from "@/lib/founder-brief-extras";
import { sendEmail } from "@/lib/email";

/**
 * Create a shareable Monetization Brief snapshot.
 * Body: { product, analysis?, pricing?, stress_test?, tool_memo?, extras?, product_blurb?, cover_note?, emailTo? }
 */
export async function POST(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  let body: {
    product?: ProductContext;
    analysis?: IdeaAnalysis | null;
    pricing?: PricingRecommendation | null;
    stress_test?: BuyerStressTestResult | null;
    tool_memo?: import("@/lib/shared-report").ToolMemo | null;
    cover_note?: string | null;
    extras?: FounderBriefExtras | null;
    product_blurb?: string | null;
    emailTo?: string;
  };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!body.product?.title || !body.product?.description) {
    return NextResponse.json(
      { error: "product title and description are required" },
      { status: 400 }
    );
  }
  if (
    !body.analysis &&
    !body.pricing &&
    !body.stress_test &&
    !body.tool_memo
  ) {
    return NextResponse.json(
      {
        error:
          "Run Analyzer, Pricing, Buyer Stress Test, or another tool brief before sharing",
      },
      { status: 400 }
    );
  }

  const payload: SharedReportPayload = buildSharedReportPayload({
    product: body.product,
    analysis: body.analysis,
    pricing: body.pricing,
    stress_test: body.stress_test,
    tool_memo: body.tool_memo,
    cover_note: body.cover_note,
    extras: body.extras,
    product_blurb: body.product_blurb,
  });
  const token = newShareToken();
  const title = `Monetization Brief: ${body.product.title}`;

  const { data, error } = await supabase
    .from("shared_reports")
    .insert({
      user_id: user.id,
      token,
      title,
      payload,
    })
    .select("id, token, created_at")
    .single();

  if (error || !data) {
    console.error("shared_reports insert failed:", error);
    const missing =
      typeof error?.message === "string" &&
      /relation .* does not exist|schema cache/i.test(error.message);
    return NextResponse.json(
      {
        error: missing
          ? "Database is missing shared_reports. Run supabase/shared_reports.sql in the Supabase SQL editor, then try again."
          : "Could not create share link. Try again.",
      },
      { status: 500 }
    );
  }

  const origin =
    process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") ||
    new URL(request.url).origin;
  const shareUrl = `${origin}/r/${data.token}`;

  let emailed = false;
  const emailTo = body.emailTo?.trim();
  if (emailTo && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailTo)) {
    const result = await sendEmail({
      to: emailTo,
      subject: title,
      text: `Your Monetization Brief for ${body.product.title} is ready:\n\n${shareUrl}\n\nGenerated by Make it RAIN.`,
      html: `
        <div style="font-family:Georgia,serif;max-width:560px;margin:0 auto;color:#1a1a1a">
          <p style="font-size:13px;letter-spacing:0.08em;text-transform:uppercase;color:#555">Make it RAIN</p>
          <h1 style="font-size:22px;line-height:1.3;margin:8px 0 16px">Monetization Brief</h1>
          <p style="font-size:16px;margin:0 0 8px"><strong>${escapeHtml(body.product.title)}</strong></p>
          <p style="font-size:14px;color:#444;margin:0 0 20px">Your professional brief is ready to view online.</p>
          <p><a href="${shareUrl}" style="display:inline-block;background:#0f172a;color:#fff;text-decoration:none;padding:12px 18px;border-radius:6px;font-size:14px">Open brief</a></p>
          <p style="font-size:12px;color:#777;margin-top:24px">${escapeHtml(shareUrl)}</p>
        </div>
      `,
    });
    emailed = result.sent;
  }

  return NextResponse.json({
    id: data.id,
    token: data.token,
    shareUrl,
    emailed,
  });
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
