/** 89-account roster for /admin/counter/v3. Statuses must tally to LIVE snapshot. */

export type RosterRow = {
  name: string;
  email: string;
  status: "trialing" | "reviewer" | "active" | "canceled" | null;
  tier: "starter" | "growth" | "pro" | null;
  daysAgo: number;
  hour: number;
  min: number;
};

export const V3_ROSTER: RosterRow[] = [
  // Today / past week (11)
  { name: "Elena Voss", email: "elena@grayline.app", status: null, tier: null, daysAgo: 0, hour: 16, min: 42 },
  { name: "Marcus Hale", email: "marcus.hale@gmail.com", status: "trialing", tier: "starter", daysAgo: 0, hour: 9, min: 18 },
  { name: "Priya Raman", email: "priya@stacklane.io", status: "trialing", tier: "starter", daysAgo: 1, hour: 21, min: 5 },
  { name: "Riya Kapoor", email: "riya@kapoor.studio", status: "trialing", tier: "starter", daysAgo: 1, hour: 14, min: 27 },
  { name: "Jonah Ellis", email: "jonah@ellismail.co", status: "trialing", tier: "starter", daysAgo: 2, hour: 23, min: 11 },
  { name: "Chris Adelman", email: "chris@adelman.io", status: "reviewer", tier: "pro", daysAgo: 2, hour: 17, min: 40 },
  { name: "Dana Ruiz", email: "dana@ruizmade.com", status: null, tier: null, daysAgo: 3, hour: 19, min: 2 },
  { name: "Devon Burke", email: "devon@burkehq.com", status: "trialing", tier: "starter", daysAgo: 3, hour: 13, min: 16 },
  { name: "Hannah Cho", email: "hannah.cho@outlook.com", status: "trialing", tier: "starter", daysAgo: 4, hour: 20, min: 48 },
  { name: "Luis Ortega", email: "luis@ortega.dev", status: "trialing", tier: "starter", daysAgo: 5, hour: 16, min: 11 },
  { name: "Amira Haddad", email: "amira@haddad.co", status: "trialing", tier: "growth", daysAgo: 5, hour: 11, min: 9 },
  // Rest of this month
  { name: "Noah Pell", email: "noah.pell@gmail.com", status: "trialing", tier: "starter", daysAgo: 7, hour: 8, min: 33 },
  { name: "Sofia Marin", email: "sofia@marincode.com", status: "trialing", tier: "starter", daysAgo: 7, hour: 16, min: 21 },
  { name: "Kenji Mori", email: "kenji@morilabs.jp", status: "active", tier: "growth", daysAgo: 7, hour: 10, min: 4 },
  { name: "Jordan Lee", email: "jordan@hey.com", status: "trialing", tier: "starter", daysAgo: 8, hour: 22, min: 19 },
  { name: "Min Park", email: "min@parkline.dev", status: "reviewer", tier: "pro", daysAgo: 8, hour: 10, min: 12 },
  { name: "Grace Whitaker", email: "grace.whitaker@gmail.com", status: "trialing", tier: "starter", daysAgo: 8, hour: 14, min: 55 },
  { name: "Cole Winters", email: "cole.winters@gmail.com", status: "trialing", tier: "growth", daysAgo: 9, hour: 19, min: 12 },
  { name: "Brett Lang", email: "brett@langworks.io", status: null, tier: null, daysAgo: 9, hour: 11, min: 18 },
  { name: "Tom Hale", email: "tom@northfold.io", status: "trialing", tier: "starter", daysAgo: 9, hour: 11, min: 40 },
  { name: "Imani Brooks", email: "imani@brooksware.com", status: "trialing", tier: "starter", daysAgo: 10, hour: 7, min: 28 },
  { name: "Leila Nasser", email: "leila@nasser.digital", status: "active", tier: "starter", daysAgo: 11, hour: 15, min: 49 },
  { name: "Benito Cruz", email: "benito@cruz.build", status: "trialing", tier: "starter", daysAgo: 12, hour: 11, min: 3 },
  { name: "Asha Patel", email: "asha.patel@gmail.com", status: "active", tier: "pro", daysAgo: 13, hour: 16, min: 37 },
  { name: "Felix Grant", email: "felix@grantworks.io", status: "trialing", tier: "growth", daysAgo: 13, hour: 13, min: 22 },
  { name: "Nadia Rahman", email: "nadia@rahman.app", status: "trialing", tier: "starter", daysAgo: 14, hour: 9, min: 58 },
  { name: "Nia Cole", email: "nia@colehouse.app", status: null, tier: null, daysAgo: 14, hour: 8, min: 41 },
  { name: "Yuki Tanaka", email: "yuki@tanaka.systems", status: "trialing", tier: "starter", daysAgo: 15, hour: 20, min: 14 },
  { name: "Adebola Okafor", email: "adebola@okafor.studio", status: "reviewer", tier: "pro", daysAgo: 15, hour: 14, min: 22 },
  { name: "Rosa Diaz", email: "rosa@diazform.com", status: "trialing", tier: "starter", daysAgo: 21, hour: 8, min: 41 },
  { name: "Peter Holm", email: "peter.holm@hey.com", status: "active", tier: "starter", daysAgo: 34, hour: 14, min: 7 },
  { name: "Sam Okonkwo", email: "sam@okonkwo.co", status: "trialing", tier: "pro", daysAgo: 18, hour: 17, min: 26 },
  { name: "Hana Kim", email: "hana@kimstack.com", status: "trialing", tier: "growth", daysAgo: 18, hour: 10, min: 51 },
  { name: "Omar Farouk", email: "omar@farouk.tech", status: "trialing", tier: "starter", daysAgo: 22, hour: 14, min: 7 },
  { name: "Ingrid Foss", email: "ingrid@fosslabs.no", status: "trialing", tier: "starter", daysAgo: 23, hour: 19, min: 33 },
  { name: "Tyler Brooks", email: "tyler.brooks@gmail.com", status: "trialing", tier: "pro", daysAgo: 26, hour: 8, min: 12 },
  // Older (before this calendar month if today is the 21st)
  { name: "Casey Nguyen", email: "casey@nguyenworks.com", status: "active", tier: "pro", daysAgo: 22, hour: 15, min: 2 },
  { name: "Sara Lind", email: "sara@lindmail.se", status: "reviewer", tier: "pro", daysAgo: 22, hour: 9, min: 8 },
  { name: "Ruth Okada", email: "ruth@okada.studio", status: "trialing", tier: "starter", daysAgo: 23, hour: 13, min: 12 },
  { name: "Andre Silva", email: "andre@silva.cc", status: "trialing", tier: "starter", daysAgo: 24, hour: 16, min: 29 },
  { name: "Lila Jensen", email: "lila.jensen@outlook.com", status: "active", tier: "starter", daysAgo: 25, hour: 8, min: 6 },
  { name: "Maya Chen", email: "maya.chen@proton.me", status: "canceled", tier: "starter", daysAgo: 26, hour: 18, min: 53 },
  { name: "Owen Drake", email: "owen.drake@icloud.com", status: "canceled", tier: "starter", daysAgo: 27, hour: 12, min: 37 },
  { name: "Hugo Stein", email: "hugo@steincraft.co", status: null, tier: null, daysAgo: 28, hour: 15, min: 3 },
  { name: "Shift Nook", email: "hello@shiftnook.app", status: "trialing", tier: "starter", daysAgo: 28, hour: 10, min: 14 },
  { name: "Sam Ellis", email: "sam@orchardlane.co", status: "trialing", tier: "growth", daysAgo: 29, hour: 15, min: 2 },
  { name: "Nina Alvarez", email: "nina@alvarez.codes", status: "trialing", tier: "starter", daysAgo: 27, hour: 11, min: 8 },
  { name: "Gia Romano", email: "gia@romanoware.com", status: "trialing", tier: "growth", daysAgo: 28, hour: 9, min: 44 },
  { name: "Wes Parker", email: "wes@parkerlabs.io", status: "active", tier: "growth", daysAgo: 32, hour: 17, min: 21 },
  { name: "Tara Singh", email: "tara.singh@gmail.com", status: "active", tier: "starter", daysAgo: 33, hour: 10, min: 5 },
  { name: "Quentin Marsh", email: "quentin@marshlab.io", status: "reviewer", tier: "pro", daysAgo: 35, hour: 16, min: 55 },
  { name: "Blair Nguyen", email: "blair@nguyencode.com", status: "active", tier: "starter", daysAgo: 36, hour: 13, min: 18 },
  { name: "Caleb Frost", email: "caleb@frostbyte.app", status: "active", tier: "growth", daysAgo: 38, hour: 11, min: 47 },
  { name: "Mei Huang", email: "mei@huanglabs.com", status: "active", tier: "starter", daysAgo: 39, hour: 19, min: 2 },
  { name: "Jules Abram", email: "jules@abram.co", status: "canceled", tier: "growth", daysAgo: 41, hour: 9, min: 14 },
  { name: "Nora Blake", email: "nora@blakehq.com", status: "active", tier: "pro", daysAgo: 42, hour: 14, min: 33 },
  { name: "Ivy Chen", email: "ivy@chenbyte.com", status: "reviewer", tier: "pro", daysAgo: 44, hour: 12, min: 30 },
  { name: "Pavel Novak", email: "pavel@novak.codes", status: "active", tier: "starter", daysAgo: 45, hour: 8, min: 16 },
  { name: "Reese Dalton", email: "reese@dalton.io", status: "active", tier: "growth", daysAgo: 47, hour: 16, min: 41 },
  { name: "Amina Shah", email: "amina@shahworks.com", status: "active", tier: "starter", daysAgo: 48, hour: 10, min: 9 },
  { name: "Theo Barr", email: "theo@barrline.app", status: "active", tier: "starter", daysAgo: 50, hour: 18, min: 22 },
  { name: "Lina Ortiz", email: "lina@ortizstudio.com", status: "active", tier: "growth", daysAgo: 52, hour: 12, min: 51 },
  { name: "Markus Feld", email: "markus@feld.co", status: "active", tier: "starter", daysAgo: 54, hour: 9, min: 37 },
  { name: "Sasha Quinn", email: "sasha@quinnmade.io", status: "active", tier: "pro", daysAgo: 56, hour: 15, min: 4 },
  { name: "Diego Vargas", email: "diego@vargas.dev", status: "active", tier: "starter", daysAgo: 58, hour: 11, min: 28 },
  { name: "Rafael Costa", email: "rafael@costa.build", status: "reviewer", tier: "pro", daysAgo: 60, hour: 18, min: 4 },
  { name: "Polly Grant", email: "polly@grantand.co", status: "active", tier: "growth", daysAgo: 61, hour: 13, min: 15 },
  { name: "Ian Brooks", email: "ian.brooks@gmail.com", status: "active", tier: "starter", daysAgo: 63, hour: 8, min: 49 },
  { name: "Yara Haddad", email: "yara@haddad.io", status: "active", tier: "starter", daysAgo: 65, hour: 16, min: 2 },
  { name: "Colin Myers", email: "colin@myerslab.com", status: "active", tier: "growth", daysAgo: 67, hour: 10, min: 21 },
  { name: "Freya Nilsen", email: "freya@nilsen.no", status: "active", tier: "starter", daysAgo: 69, hour: 14, min: 38 },
  { name: "Omar Syed", email: "omar.syed@outlook.com", status: "active", tier: "starter", daysAgo: 71, hour: 9, min: 11 },
  { name: "Kate Bloom", email: "kate@bloompath.app", status: "active", tier: "growth", daysAgo: 73, hour: 17, min: 44 },
  { name: "Neil Kapoor", email: "neil@kapoor.cc", status: "active", tier: "pro", daysAgo: 75, hour: 12, min: 6 },
  { name: "Rita Gomez", email: "rita@gomez.works", status: "active", tier: "starter", daysAgo: 76, hour: 8, min: 29 },
  { name: "Helen Ward", email: "helen@wardnote.com", status: "reviewer", tier: "pro", daysAgo: 78, hour: 11, min: 19 },
  { name: "Jon Park", email: "jon@parkfield.io", status: "active", tier: "starter", daysAgo: 80, hour: 15, min: 52 },
  { name: "Mira Joshi", email: "mira@joshilab.com", status: "active", tier: "growth", daysAgo: 82, hour: 10, min: 14 },
  { name: "Ed Walsh", email: "ed@walshcodes.com", status: "active", tier: "starter", daysAgo: 84, hour: 13, min: 41 },
  { name: "Tova Klein", email: "tova@klein.app", status: "active", tier: "starter", daysAgo: 86, hour: 9, min: 7 },
  { name: "Chris Yoon", email: "chris@yoonmade.com", status: "active", tier: "growth", daysAgo: 88, hour: 16, min: 23 },
  { name: "Paula Reed", email: "paula@reedcraft.io", status: "active", tier: "starter", daysAgo: 90, hour: 11, min: 55 },
  { name: "Nico Brandt", email: "nico@brandt.dev", status: "active", tier: "starter", daysAgo: 93, hour: 8, min: 18 },
  { name: "Drew Patel", email: "drew@patelcraft.io", status: "active", tier: "starter", daysAgo: 96, hour: 14, min: 22 },
  { name: "Ava Moreau", email: "ava@moreau.studio", status: "trialing", tier: "pro", daysAgo: 24, hour: 8, min: 11 },
  { name: "Leon Hart", email: "leon@hartline.io", status: "trialing", tier: "growth", daysAgo: 25, hour: 19, min: 40 },
  { name: "Pia Solis", email: "pia@solis.co", status: "trialing", tier: "starter", daysAgo: 21, hour: 12, min: 6 },
  { name: "Omar Klein", email: "omar@kleinworks.com", status: "trialing", tier: "pro", daysAgo: 29, hour: 7, min: 51 },
  { name: "Rita Lang", email: "rita@langbyte.com", status: "trialing", tier: "growth", daysAgo: 25, hour: 18, min: 3 },
];
