import type { IdeaAnalysis, PricingRecommendation } from "@/types";
import {
  listEvidenceSources,
  type ProductContext,
} from "@/lib/product-context";

function bullets(items: string[] | undefined): string {
  if (!items?.length) return "_None_";
  return items.map((i) => `- ${i}`).join("\n");
}

/** Markdown Monetization Brief for export / investor-style sharing. */
export function buildMonetizationBriefMd(input: {
  product: ProductContext;
  analysis?: IdeaAnalysis | null;
  pricing?: PricingRecommendation | null;
}): string {
  const { product, analysis, pricing } = input;
  const lines: string[] = [
    `# Monetization Brief: ${product.title}`,
    "",
    `_Generated by Make it RAIN · ${new Date().toISOString().slice(0, 10)}_`,
    "",
    "## Product",
    "",
    `- **Type:** ${product.type}`,
  ];
  if (product.stage) lines.push(`- **Stage:** ${product.stage}`);
  if (product.current_price) {
    lines.push(`- **Current price:** ${product.current_price}`);
  }
  if (product.product_url) {
    lines.push(`- **Product URL:** ${product.product_url}`);
  }
  if (product.github_repo_url) {
    lines.push(`- **GitHub:** ${product.github_repo_url}`);
  }
  lines.push("", product.description, "");

  lines.push(
    "## Evidence inventory",
    "",
    ...listEvidenceSources(product).map((s) => `- ${s}`),
    "",
    "_Claims below should be read against this inventory. Unsupported points are assumptions, not verified facts._",
    ""
  );

  if (product.website_context) {
    const w = product.website_context;
    lines.push("## Product URL scrape", "");
    lines.push(`- **Fetched:** ${w.fetched_at.slice(0, 10)}`);
    lines.push(`- **Final URL:** ${w.final_url}`);
    if (w.title) lines.push(`- **Page title:** ${w.title}`);
    if (w.meta_description) lines.push(`- **Meta:** ${w.meta_description}`);
    lines.push("", "### Page excerpt", "", w.text_excerpt.slice(0, 2500), "");
  }

  if (product.traction?.trim()) {
    lines.push("## Traction", "", product.traction.trim(), "");
  }
  if (product.competitors_notes?.trim()) {
    lines.push(
      "## Known competitors",
      "",
      product.competitors_notes.trim(),
      ""
    );
  }

  if (analysis) {
    lines.push(
      "## Commercial assessment",
      "",
      `**Score:** ${analysis.score}/10`,
      "",
      analysis.score_reasoning,
      ""
    );
    if (analysis.confidence) {
      lines.push(`**Confidence:** ${analysis.confidence}`, "");
    }
    lines.push("### Big promise", "", `> ${analysis.big_promise}`, "");
    if (analysis.assumptions?.length) {
      lines.push("### Assumptions", "", bullets(analysis.assumptions), "");
    }
    if (analysis.kill_criteria?.length) {
      lines.push("### Kill criteria", "", bullets(analysis.kill_criteria), "");
    }
    lines.push("### Paths", "");
    for (const path of analysis.recommended_paths ?? []) {
      lines.push(
        `- **${path.name}** (${path.effort} effort / ${path.revenue_potential} revenue) — ${path.description}`
      );
    }
    lines.push("", "### Quick wins", "", bullets(analysis.quick_wins), "");
    if (analysis.validation_plan?.length) {
      lines.push(
        "### Validation plan",
        "",
        bullets(analysis.validation_plan),
        ""
      );
    }
    if (analysis.citations?.length) {
      lines.push("### Evidence grades", "");
      for (const c of analysis.citations) {
        lines.push(`- **[${c.grade}]** ${c.claim} _(source: ${c.source})_`);
      }
      lines.push("");
    }
    if (analysis.competitor_enrichment?.length) {
      lines.push("### Competitor firmographics", "");
      for (const row of analysis.competitor_enrichment) {
        lines.push(
          `- **${row.name}** — ${[row.industry, row.domain, row.employeeCount != null ? `~${row.employeeCount} emp` : null].filter(Boolean).join(" · ") || "no match"}`
        );
      }
      lines.push("");
    }
  }

  if (pricing) {
    lines.push(
      "## Pricing economics",
      "",
      `**Recommended model:** ${pricing.recommended_model.replace("_", "-")}`,
      "",
      pricing.model_reasoning,
      ""
    );
    if (pricing.willingness_to_pay_logic) {
      lines.push(
        "### Willingness to pay",
        "",
        pricing.willingness_to_pay_logic,
        ""
      );
    }
    lines.push("### Price ranges", "");
    for (const r of pricing.price_ranges ?? []) {
      lines.push(
        `- **${r.label}:** $${r.sweet_spot} (range $${r.low}–$${r.high}) — ${r.notes}`
      );
    }
    lines.push("");
    if (pricing.packaging_tradeoffs?.length) {
      lines.push(
        "### Packaging tradeoffs",
        "",
        bullets(pricing.packaging_tradeoffs),
        ""
      );
    }
    if (pricing.pricing_experiment) {
      lines.push(
        "### Pricing experiment",
        "",
        pricing.pricing_experiment,
        ""
      );
    }
    if (pricing.value_anchors?.length) {
      lines.push("### Value anchors", "", bullets(pricing.value_anchors), "");
    }
    const copy = pricing.sales_copy;
    if (copy) {
      lines.push(
        "### Sales copy draft",
        "",
        `**${copy.headline}**`,
        "",
        copy.subheadline,
        "",
        bullets(copy.bullets?.map((b) => b) ?? []),
        "",
        `CTA: ${copy.cta}`,
        ""
      );
    }
  }

  lines.push(
    "---",
    "",
    "_Directional strategy memo — validate with buyers before committing capital._"
  );
  return lines.join("\n");
}
